services:
  order-service:
    build:
      context: ./app/order-service
    container_name: ${ORDER_SERVICE_NAME}
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      PORT: ${ORDER_SERVICE_PORT}
      SERVICE_NAME: ${ORDER_SERVICE_NAME}
    networks:
      - watchtower-net
    logging:
      driver: json-file

  tracking-service:
    build:
      context: ./app/tracking-service
    container_name: ${TRACKING_SERVICE_NAME}
    ports:
      - "${TRACKING_SERVICE_PORT}:${TRACKING_SERVICE_PORT}"
    environment:
      PORT: ${TRACKING_SERVICE_PORT}
      SERVICE_NAME: ${TRACKING_SERVICE_NAME}
    networks:
      - watchtower-net
    logging:
      driver: json-file

  notification-service:
    build:
      context: ./app/notification-service
    container_name: ${NOTIFICATION_SERVICE_NAME}
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    environment:
      PORT: ${NOTIFICATION_SERVICE_PORT}
      SERVICE_NAME: ${NOTIFICATION_SERVICE_NAME}
    networks:
      - watchtower-net
    logging:
      driver: json-file

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - order-service
      - tracking-service
      - notification-service    
    networks:
      - watchtower-net  

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - watchtower-net      

networks:
  watchtower-net:
    driver: bridge
